document.writeln("<script type=\'text/javascript\'> ");
document.writeln("function execClick(){");
document.writeln("    document.execCommand(\'copy\');");
document.writeln("}");
document.writeln("");
document.writeln("function execCopy(event,thisDiv){");
document.writeln("    if(isIE()){");
document.writeln("        if(window.clipboardData){");
document.writeln("            window.clipboardData.setData(\'Text\', thisDiv.textContent);");
document.writeln("            alert(window.clipboardData.getData(\'Text\'));");
document.writeln("        }");
document.writeln("    }else{");
document.writeln("        event.preventDefault();");
document.writeln("        if (event.clipboardData) {");
document.writeln("            event.clipboardData.setData(\'text/plain\', thisDiv.textContent);");
document.writeln("            alert(event.clipboardData.getData(\'text\'));");
document.writeln("        }");
document.writeln("    }");
document.writeln("}");
document.writeln("");
document.writeln("function isIE(){");
document.writeln("    var input = window.document.createElement (\'input\');");
document.writeln("    /*\'!window.ActiveXObject\' is evaluated to true in IE11*/");
document.writeln("    if (window.ActiveXObject === undefined) return null;");
document.writeln("    if (!window.XMLHttpRequest) return 6;");
document.writeln("    if (!window.document.querySelector) return 7;");
document.writeln("    if (!window.document.addEventListener) return 8;");
document.writeln("    if (!window.atob) return 9;");
document.writeln("    /*\'!window.document.body.dataset\' is faster but the body is null when the DOM is not ready. Anyway, an input tag needs to be created to check if IE is being emulated*/");
document.writeln("    if (!input.dataset) return 10;");
document.writeln("    return 11;");
document.writeln("}");
document.writeln("</script> ");