#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-down.local instead
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH
LOGDEVICE=$6
REALDEVICE=$1
/etc/ppp/ip-down.ipv6to4 ${LOGDEVICE}
[ -x /etc/ppp/ip-down.local ] && /etc/ppp/ip-down.local "$@"
/etc/sysconfig/network-scripts/ifdown-post --realdevice ${REALDEVICE} \
    ifcfg-${LOGDEVICE}
echo "downtime: `date -d today +%F_%T`" >> /var/log/VPN-${1}.log
echo "bytes sent: $BYTES_SENT B" >> /var/log/VPN-${1}.log
echo "bytes received: $BYTES_RCVD B" >> /var/log/VPN-${1}.log
sum_bytes=$(($BYTES_SENT+$BYTES_RCVD))
sum=`echo "scale=2;$sum_bytes/1024/1024"|bc`
echo "bytes sum: $sum MB" >> /var/log/VPN-${1}.log
ave=`echo "scale=2;$sum_bytes/1024/$CONNECT_TIME"|bc`
echo "average speed: $ave KB/s" >> /var/log/VPN-${1}.log
echo "connect time: $CONNECT_TIME S" >> /var/log/VPN-${1}.log
echo "****************************************************" >> /var/log/VPN-${1}.log
