#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH
LOGDEVICE=$6
REALDEVICE=$1
[ -f /etc/sysconfig/network-scripts/ifcfg-${LOGDEVICE} ] && /etc/sysconfig/network-scripts/ifup-post --realdevice ${REALDEVICE} ifcfg-${LOGDEVICE}
/etc/ppp/ip-up.ipv6to4 ${LOGDEVICE}
[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local "$@"
echo "****************************************************" >> /var/log/VPN-${1}.log
echo "username: $PEERNAME" >> /var/log/VPN-${1}.log
echo "clientIP: $6" >> /var/log/VPN-${1}.log
echo "device: $1" >> /var/log/VPN-${1}.log
echo "vpnIP: $4" >> /var/log/VPN-${1}.log
echo "assignIP: $5" >> /var/log/VPN-${1}.log
echo "logintime: `date -d today +%F_%T`" >> /var/log/VPN-${1}.log
